import Util from '/src/config/Util';

export const args = {};
export const pages = {};
export const app = {
  setPages() {
    app.makePage('top', '/', 'Top');
    app.makePage('subpage', '/subpage', 'Subpage');
  },
  preInit() {
    args.siteName = 'Astro Site';
    args.titleSuffix = 'Generated by astro.debiru.net';
    args.description = 'Astro Site Starter Kit';
    args.twitter = '@YOUR_TWITTER_ID';
    args.lang = 'ja';
    args.locale = 'ja_JP';
    args.og_image = 'img/global/og.png';
  },
  postInit(Astro, pageArgs) {
    app.Astro = Astro;
    app.args = pageArgs ?? {};
    app.url = Astro.url;
    args.domain = app.url.hostname;
    args.path = app.url.pathname.replace(/\.html$/, '');
    const selfRoute = route(args.path);
    args.page = Object.values(pages).find((page) => page.route === selfRoute) ?? {};
    args.page.useComponents = Util.fs.getComponents(Astro.self.moduleId);
    args.url = app.url.origin + args.path;
    args.siteRootUrl = app.url.origin;
    args.siteRootUrlWithoutProtocol = app.url.host;
    args.urlWithoutProtocol = app.url.host + args.path;
    args.assetList = Object.fromEntries(['css', 'js'].map((ext) => {
      const value = [];
      const willAdd = (dir, file) => {
        const path = Util.sprintf('%s/%s.%s', dir, file, ext);
        const fileExist = Util.fs.exist(Util.sprintf('public/assets/%s/%s', ext, path));
        if (fileExist) value.push(path);
      };
      if (args.page.key) willAdd('pages', args.page.key);
      args.page.useComponents.forEach((componentName) => {
        willAdd('components', componentName);
      });
      return [ext, value];
    }));
    args.titlePrefix = app.args.title;
    args.title = (args.titlePrefix != null ? args.titlePrefix + ' - ' : '') + args.siteName + (args.titleSuffix != null ? ' | ' + args.titleSuffix : '');
    args.og_type = args.path === '/' ? 'website' : 'article';
    if (!isAbsUrl(args.og_image)) args.og_image = assetsUrl(args.og_image, true);
  },
  makePage(key, argRoute, label) {
    pages[key] = { key, route: route(argRoute), label };
  },
  init(Astro, pageArgs) {
    app.setPages();
    app.preInit();
    if (Astro) app.postInit(Astro, pageArgs);
  },
};

export const rootPath = (path) => {
  path = '/' + Util.ltrim(path);
  return path;
};

export const assets = (path, cacheBuster = false) => {
  path = rootPath('assets/' + Util.ltrim(path));
  if (cacheBuster) path += '?' + Date.now();
  return path;
};

export const assetsUrl = (path, cacheBuster = false) => {
  return Util.rtrim(app.url.origin) + assets(path, cacheBuster);
};

export const isAbsUrl = (url) => {
  return /^(?:\w+:)?\/\//.test(url);
};

export const img = (path) => {
  return assets('img/' + Util.ltrim(path));
};

export const route = (path) => {
  return Util.rtrim(rootPath(String(path))) + '/';
};
